// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIrzz6y6F6fuHXyqJ0LfUkoqhzMEN2_Tk',
    appId: '1:339155175415:web:4d1f3345d40018f96410f2',
    messagingSenderId: '339155175415',
    projectId: 'riotsync-27a90',
    authDomain: 'riotsync-27a90.firebaseapp.com',
    storageBucket: 'riotsync-27a90.appspot.com',
    measurementId: 'G-K60Z86F3ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjA0Znn4OmxUScjv8ufeaXdjsBLlXTdtc',
    appId: '1:339155175415:android:53edd0ed0b269dac6410f2',
    messagingSenderId: '339155175415',
    projectId: 'riotsync-27a90',
    storageBucket: 'riotsync-27a90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdpwD8KdVMBTOE87ZKiSncLeSHu2jRZp0',
    appId: '1:339155175415:ios:3463081696daa2996410f2',
    messagingSenderId: '339155175415',
    projectId: 'riotsync-27a90',
    storageBucket: 'riotsync-27a90.appspot.com',
    iosBundleId: 'com.example.riotSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdpwD8KdVMBTOE87ZKiSncLeSHu2jRZp0',
    appId: '1:339155175415:ios:37c8b160aa3b28926410f2',
    messagingSenderId: '339155175415',
    projectId: 'riotsync-27a90',
    storageBucket: 'riotsync-27a90.appspot.com',
    iosBundleId: 'com.example.riotSync.RunnerTests',
  );
}
